
# @Author: cole
# @Date:   2018-10-13T19:01:07-04:00
# @Last modified by:   cole
# @Last modified time: 2018-11-10T12:41:06-05:00
all:
  hosts:

#===============================================================================
# Servers
#===============================================================================
    service.cwalops.ca:
    names.cwalops.ca:
    alien.cwalops.ca:
#===============================================================================
# Switches
#===============================================================================
    sw1.cwalops.ca:
    sw2.cwalops.ca:
    sw3.cwalops.ca:
    sw31.cwalops.ca:
    sw32.cwalops.ca:

#===============================================================================
# Routers
#===============================================================================
    r1.cwalops.ca:
    r2.cwalops.ca:
    r3.cwalops.ca:

#===============================================================================
# PCs
#===============================================================================
    7erver.cwalops.ca:
    tuxlab.cwalops.ca:

  children:
    servers:
      hosts:
        service.cwalops.ca:
        names.cwalops.ca:
        alien.cwalops.ca:
    network:
      children:
        switches:
          hosts:
            sw1.cwalops.ca:
            sw2.cwalops.ca:
            sw3.cwalops.ca:
            sw31.cwalops.ca:
            sw32.cwalops.ca:
        routers:
          hosts:
            r1.cwalops.ca:
            r2.cwalops.ca:
            r3.cwalops.ca:
    pcs:
      hosts:
        7erver.cwalops.ca:
        tuxlab.cwalops.ca:
