
# @Author:                   cole
# @Date:                     2018-10-13T19:01:07-04:00
# @Last modified by:   cole
# @Last modified time: 2018-11-10T13:19:55-05:00
all:
  hosts:
    localhost:
#===============================================================================
# Servers
#===============================================================================
    virt.cwalops.ca:
    names.cwalops.ca:
    alien.cwalops.ca:
    freenas.cwalops.ca:
#===============================================================================
# Switches
#===============================================================================
    sw1.cwalops.ca:
    sw2.cwalops.ca:
    sw3.cwalops.ca:
    sw31.cwalops.ca:
    sw32.cwalops.ca:
#===============================================================================
# Routers
#===============================================================================
    r1.cwalops.ca:
    r2.cwalops.ca:
    r3.cwalops.ca:
#===============================================================================
# PCs
#===============================================================================
    tuxlab.cwalops.ca:
#===============================================================================
# Logical Groups
#===============================================================================
  children:
    servers:
      hosts:
        virt.cwalops.ca:
        names.cwalops.ca:
        alien.cwalops.ca:
        freenas.cwalops.ca:
    network:
      children:
        switches:
          hosts:
            sw1.cwalops.ca:
            sw2.cwalops.ca:
            sw3.cwalops.ca:
            sw31.cwalops.ca:
            sw32.cwalops.ca:
        routers:
          hosts:
            r1.cwalops.ca:
            r2.cwalops.ca:
            r3.cwalops.ca:
    pcs:
      hosts:
        tuxlab.cwalops.ca:
