# @Author:          cole
# @Date:            2018-11-10T13:10:50-05:00
# @Filename:        all.yml
# @Last modified by: cole
# @Last modified time: 2018-11-10T13:32:25-05:00

ssh:
  port:             '22'
  listen:           '0.0.0.0'
  root_login:       'no'
  password_auth:    'no'
  x11_forward:      'no'
  client_alive_int: '300' #send null packet every 5 mins
  client_alive_max: '6'   #disconnect ssh if inactive for 6 alive intervals
  permit_tunnel:    'no'
  banner_path:      '/etc/banner'
  # user:             # Example- used to override settings on a per user basis
  #   - name: 'cole'
  #     params:
  #       - 'X11Forwading yes'
  #       - 'PermitTTY yes'
